Module: LambdaSharp.Challenge.TheWikiGame
Description: Find a sequence of links from one Wikipedia page to another
Items:

  - Resource: LinksTable
    Description: DynamoDB table storing all found links and sequences
    Scope: FindLinksFunction
    Type: AWS::DynamoDB::Table
    Allow: ReadWrite
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH

  - Function: FindLinksFunction
    Description: >-
      Check if sequence is complete, otherwise parse new pages until
      a sequence is found or the search depth is exhausted.
    Memory: 256
    Timeout: 30
    Sources:
      - Sqs: AnalyzeQueue

  - Resource: AnalyzeQueue
    Description: Queue containing all Wikipedia pages to analyze
    Scope: FindLinksFunction
    Type: AWS::SQS::Queue
    Allow: Send,Receive

  - Resource: NotifyFoundTopic
    Description: Notification topic for sending out a found solution for The Wiki Game
    Scope: FindLinksFunction
    Type: AWS::SNS::Topic
    Allow: Publish